// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsdxTimingOverride } from "./UsdxTimingOverride";

export type UsdxCalibrationPreview = {
  timing_override: UsdxTimingOverride;
  offset_ms: number;
  bpm_delta: number;
  first_note_time_secs: number | null;
  last_note_end_secs: number | null;
  chart_audio_mismatch_secs: number | null;
};
