// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local, non-destructive USDX timing correction. Values are effective chart
 * values, not deltas, so reset can always return to the parsed TXT values.
 */
export type UsdxTimingOverride = { gap_ms: number; bpm: number };
