// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsdxTimingInfo = {
  file_hash: string;
  txt_path: string;
  txt_file_name: string;
  audio_path: string;
  audio_file_name: string;
  parsed_bpm: number;
  parsed_gap_ms: number;
  effective_bpm: number;
  effective_gap_ms: number;
  offset_ms: number;
  audio_duration_secs: number;
  first_note_time_secs: number | null;
  last_note_end_secs: number | null;
  /**
   * `last_note_end_secs - audio_duration_secs`; positive means the chart
   * extends past the audio, negative means it ends before the audio.
   */
  chart_audio_mismatch_secs: number | null;
  has_override: boolean;
};
