// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VocalCalibration = {
  profile: string;
  device_name: string;
  range_preset: string;
  pitch_offset_cents: number;
  mic_latency_ms: number;
  quality_score: number;
  valid_frame_count: number;
  transition_count: number;
  offset_mad_cents: number;
  latency_mad_ms: number;
  sequence_version: number;
  created_at: bigint;
  updated_at: bigint;
};
